# dbt-cli-dict.sh
# A helpful dictionary of dbt CLI commands/flags and their descriptions.
# Reference this file for quick reminders about the dbt command line interface!

echo "DBT CLI COMMANDS & FLAGS DICTIONARY"
echo "==================================="

echo ""
echo "General Commands:"
echo "-----------------"
echo "dbt --version"
echo "    Shows the currently installed dbt version."
echo "    Example:"
echo "        dbt --version"

echo ""
echo "dbt debug"
echo "    Tests your dbt configuration, connection, and environment setup."
echo "    Example:"
echo "        dbt debug"

echo ""
echo "dbt init [project_name]"
echo "    Initializes a new dbt project in a subdirectory called [project_name]."
echo "    Example:"
echo "        dbt init pharmacy_benefits_project"

echo ""
echo "Build & Run Commands:"
echo "---------------------"
echo "dbt run"
echo "    Executes the dbt models (build tables/views defined in models/)."
echo "    Example:"
echo "        dbt run"
echo "        dbt run --select stg_members"

echo ""
echo "dbt build"
echo "    Runs models, tests, seeds, and snapshots as a full build pipeline."
echo "    (Shortcut for: dbt run + dbt test + dbt seed + dbt snapshot)"
echo "    Example:"
echo "        dbt build"
echo "        dbt build --select tag:daily"

echo ""
echo "dbt test"
echo "    Runs tests on your data as defined in tests/ and inside model files."
echo "    Example:"
echo "        dbt test"
echo "        dbt test -s stg_claims"

echo ""
echo "dbt seed"
echo "    Loads CSV seed files located in the seeds/ directory into your warehouse."
echo "    Example:"
echo "        dbt seed"
echo "        dbt seed --select member_seed"

echo ""
echo "dbt snapshot"
echo "    Executes snapshot logic to track changes in snapshot tables over time."
echo "    Example:"
echo "        dbt snapshot"

echo ""
echo "Source & Documentation Commands:"
echo "-------------------------------"
echo "dbt source freshness"
echo "    Checks the freshness of your source data (run on sources with freshness specified)."
echo "    Example:"
echo "        dbt source freshness"

echo ""
echo "dbt docs generate"
echo "    Generates documentation for your dbt project."
echo "    Example:"
echo "        dbt docs generate"

echo ""
echo "dbt docs serve"
echo "    Serves the documentation locally at http://localhost:8080."
echo "    Example:"
echo "        dbt docs serve"

echo ""
echo "Cleaning and Compilation:"
echo "------------------------"
echo "dbt clean"
echo "    Deletes compiled files and cleans up the dbt environment."
echo "    Example:"
echo "        dbt clean"

echo ""
echo "dbt compile"
echo "    Compiles your dbt models without running them (renders SQL into target/)."
echo "    Example:"
echo "        dbt compile"
echo "        dbt compile -s stg_plans"

echo ""
echo "Flags & Options:"
echo "---------------"
echo "--profiles-dir [DIR]"
echo "    Override the directory where dbt looks for the profiles.yml file."
echo "    Example:"
echo "        dbt run --profiles-dir /path/to/custom/profiles"

echo ""
echo "--project-dir [DIR]"
echo "    Override the directory of the dbt project (default: current directory)."
echo "    Example:"
echo "        dbt run --project-dir /path/to/dbt/project"

echo ""
echo "--select [model/table/tag]"
echo "-s [model/table/tag]"
echo "    Selects specific resources (models, sources, snapshots, tests, etc.) to run/compile/test."
echo "    Example:"
echo "        dbt run --select stg_claims"
echo "        dbt test -s stg_members"
echo "        dbt build --select tag:incremental"

echo ""
echo "--exclude [model/table/tag]"
echo "-x [model/table/tag]"
echo "    Excludes specific resources from a run/compile/test."
echo "    Example:"
echo "        dbt run --exclude stg_providers"
echo "        dbt build -x tag:monthly"

echo ""
echo "--full-refresh"
echo "    Drops incremental models and re-creates them from scratch."
echo "    Example:"
echo "        dbt run --full-refresh"
echo "        dbt build --full-refresh"

echo ""
echo "--target [target-name]"
echo "    Use a profile target other than the default."
echo "    Example:"
echo "        dbt run --target prod"
echo "        dbt test --target dev"

echo ""
echo "--vars '{\"var_name\": \"value\"}'"
echo "    Pass variables (as a JSON string) to your dbt project."
echo "    Example:"
echo "        dbt run --vars '{\"year\": 2024}'"
echo "        dbt build --vars '{\"env\": \"test\"}'"

echo ""
echo "--threads [N]"
echo "    Sets the number of threads dbt uses while running models."
echo "    Example:"
echo "        dbt run --threads 8"
echo "        dbt build --threads 2"

echo ""
echo "dbt-codegen"
echo "---------------------"
echo "dbt run-operation generate_source --args '{\"schema_name\": \"claims\", \"database_name\": \"pharmacy_benefits_raw\", \"generate_columns\": true}'"
echo "    Example:"
echo "        dbt run-operation generate_source --args '{\"schema_name\": \"providers\", \"database_name\": \"pharmacy_benefits_raw\", \"generate_columns\": true}'"

echo ""
echo "More Info:"
echo "----------"
echo "See the dbt docs for more: https://docs.getdbt.com/reference/commands"