-- ============================================================
-- cleanup_wrong_schemas.sql
-- Drop dbt schemas created by default generate_schema_name concatenation.
-- Run once after deploying macros/generate_schema_name.sql.
-- Keep: PHARMACY_BENEFITS_DEV.DBT_JMOORE
-- Keep: PHARMACY_BENEFITS_PROD.STAGING, INTERMEDIATE, MARTS, SNAPSHOTS
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Dev: drop suffixed schemas
USE DATABASE PHARMACY_BENEFITS_DEV;

DROP SCHEMA IF EXISTS DBT_JMOORE_STAGING CASCADE;
DROP SCHEMA IF EXISTS DBT_JMOORE_INTERMEDIATE CASCADE;
DROP SCHEMA IF EXISTS DBT_JMOORE_MARTS CASCADE;

-- Prod: drop concatenated / stray schemas
USE DATABASE PHARMACY_BENEFITS_PROD;

DROP SCHEMA IF EXISTS MARTS_STAGING CASCADE;
DROP SCHEMA IF EXISTS MARTS_INTERMEDIATE CASCADE;
DROP SCHEMA IF EXISTS MARTS_MARTS CASCADE;
DROP SCHEMA IF EXISTS MARTS CASCADE;

DROP SCHEMA IF EXISTS STAGING_STAGING CASCADE;
DROP SCHEMA IF EXISTS STAGING_INTERMEDIATE CASCADE;
DROP SCHEMA IF EXISTS STAGING_MARTS CASCADE;
