-- ============================================================
-- setup_prod.sql
-- Snowflake setup for dbt prod environment
-- Project: pharmacy_benefits
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ------------------------------------------------------------
-- 1. Create dbt prod role
-- ------------------------------------------------------------

CREATE ROLE IF NOT EXISTS DBT_PROD_ROLE;

-- Grant role to your Snowflake user
GRANT ROLE DBT_PROD_ROLE TO USER JMOORE87JR;

-- Optional: allow prod role to inherit dev role privileges
-- This assumes DBT_DEV_ROLE already exists from setup_dev.sql.
GRANT ROLE DBT_DEV_ROLE TO ROLE DBT_PROD_ROLE;

-- ------------------------------------------------------------
-- 2. Create prod warehouse
-- ------------------------------------------------------------

CREATE WAREHOUSE IF NOT EXISTS DBT_PROD_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE DBT_PROD_WH TO ROLE DBT_PROD_ROLE;

-- Optional: allow prod role to use dev warehouse too
-- This assumes DBT_DEV_WH already exists from setup_dev.sql.
GRANT USAGE ON WAREHOUSE DBT_DEV_WH TO ROLE DBT_PROD_ROLE;

-- ------------------------------------------------------------
-- 3. Create prod database
-- ------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS PHARMACY_BENEFITS_PROD;

GRANT USAGE ON DATABASE PHARMACY_BENEFITS_PROD TO ROLE DBT_PROD_ROLE;

-- Allow dbt prod role to create prod schemas if needed
GRANT CREATE SCHEMA ON DATABASE PHARMACY_BENEFITS_PROD TO ROLE DBT_PROD_ROLE;

-- ------------------------------------------------------------
-- 4. Create prod schemas
-- ------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_PROD.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_PROD.MARTS;
CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_PROD.SNAPSHOTS;

GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_PROD.STAGING TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_PROD.INTERMEDIATE TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_PROD.MARTS TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_PROD.SNAPSHOTS TO ROLE DBT_PROD_ROLE;

GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_PROD.STAGING TO ROLE DBT_PROD_ROLE;
GRANT CREATE VIEW ON SCHEMA PHARMACY_BENEFITS_PROD.STAGING TO ROLE DBT_PROD_ROLE;

GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_PROD.INTERMEDIATE TO ROLE DBT_PROD_ROLE;
GRANT CREATE VIEW ON SCHEMA PHARMACY_BENEFITS_PROD.INTERMEDIATE TO ROLE DBT_PROD_ROLE;

GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_PROD.MARTS TO ROLE DBT_PROD_ROLE;
GRANT CREATE VIEW ON SCHEMA PHARMACY_BENEFITS_PROD.MARTS TO ROLE DBT_PROD_ROLE;

GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_PROD.SNAPSHOTS TO ROLE DBT_PROD_ROLE;
GRANT CREATE VIEW ON SCHEMA PHARMACY_BENEFITS_PROD.SNAPSHOTS TO ROLE DBT_PROD_ROLE;

-- Optional but useful for seeds, external stages, and generated objects
GRANT CREATE STAGE ON SCHEMA PHARMACY_BENEFITS_PROD.STAGING TO ROLE DBT_PROD_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA PHARMACY_BENEFITS_PROD.STAGING TO ROLE DBT_PROD_ROLE;

GRANT CREATE STAGE ON SCHEMA PHARMACY_BENEFITS_PROD.MARTS TO ROLE DBT_PROD_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA PHARMACY_BENEFITS_PROD.MARTS TO ROLE DBT_PROD_ROLE;

-- ------------------------------------------------------------
-- 5. Future grants for objects created by dbt
-- ------------------------------------------------------------

GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_PROD.STAGING TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_PROD.STAGING TO ROLE DBT_PROD_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_PROD.INTERMEDIATE TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_PROD.INTERMEDIATE TO ROLE DBT_PROD_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_PROD.MARTS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_PROD.MARTS TO ROLE DBT_PROD_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_PROD.SNAPSHOTS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_PROD.SNAPSHOTS TO ROLE DBT_PROD_ROLE;