-- ============================================================
-- setup_raw.sql
-- Snowflake setup for raw/source data
-- Project: pharmacy_benefits
--
-- Purpose:
--   Stores unmodeled source data that dbt reads from using source().
--   dbt dev/prod models should transform data out of RAW and into
--   PHARMACY_BENEFITS_DEV / PHARMACY_BENEFITS_PROD.
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ------------------------------------------------------------
-- 1. Create raw database
-- ------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS PHARMACY_BENEFITS_RAW;

-- ------------------------------------------------------------
-- 2. Create raw schemas by source/domain
-- ------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_RAW.CLAIMS;
CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_RAW.MEMBERS;
CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_RAW.PHARMACIES;
CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_RAW.DRUGS;
CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_RAW.PLANS;
CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_RAW.PROVIDERS;
CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_RAW.REFERENCE;

-- Optional catch-all schema for early exploration / one-off CSV loads
CREATE SCHEMA IF NOT EXISTS PHARMACY_BENEFITS_RAW.RAW;

-- ------------------------------------------------------------
-- 3. Grant database usage to dbt roles
-- ------------------------------------------------------------

GRANT USAGE ON DATABASE PHARMACY_BENEFITS_RAW TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON DATABASE PHARMACY_BENEFITS_RAW TO ROLE DBT_PROD_ROLE;

-- ------------------------------------------------------------
-- 4. Grant schema usage to dbt roles
-- ------------------------------------------------------------

GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_DEV_ROLE;

GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_PROD_ROLE;

-- ------------------------------------------------------------
-- 5. Grant read access on existing raw objects
-- ------------------------------------------------------------

GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_DEV_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_DEV_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_PROD_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_PROD_ROLE;

-- ------------------------------------------------------------
-- 6. Grant read access on future raw objects
-- ------------------------------------------------------------

GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_DEV_ROLE;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_DEV_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_PROD_ROLE;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_PROD_ROLE;

-- ------------------------------------------------------------
-- 7. Allow dev role to create/load raw objects for this practice project
-- ------------------------------------------------------------
-- In a real production setup, raw loading would usually be handled by
-- a separate loader role, ELT tool role, or ingestion service account.
-- For this solo project, DBT_DEV_ROLE can create source tables.

GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_RAW.CLAIMS TO ROLE DBT_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_RAW.MEMBERS TO ROLE DBT_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_RAW.PHARMACIES TO ROLE DBT_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_RAW.DRUGS TO ROLE DBT_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_RAW.PLANS TO ROLE DBT_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_RAW.PROVIDERS TO ROLE DBT_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_RAW.REFERENCE TO ROLE DBT_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_DEV_ROLE;

GRANT CREATE STAGE ON SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_DEV_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA PHARMACY_BENEFITS_RAW.RAW TO ROLE DBT_DEV_ROLE;